export const UI_IS_LOADING = 'UI_IS_LOADING'
export const UI_FINISHED_LOADING = 'UI_FINISHED_LOADING'

export const UI_MOBILE_NAVBAR_ACTIVATE = 'UI_MOBILE_NAVBAR_ACTIVATE'
export const UI_MOBILE_NAVBAR_DEACTIVATE = 'UI_MOBILE_NAVBAR_DEACTIVATE'

export const UI_MOBILE_NAVBAR_TOGGLE = 'UI_MOBILE_NAVBAR_TOGGLE'
