export const AUTH_CHECK = 'AUTH_CHECK'

export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER'
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS'
export const AUTH_LOGIN_USER_FAILED = 'AUTH_LOGIN_USER_FAILED'

export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER'
export const AUTH_LOGOUT_USER_SUCCESS = 'AUTH_LOGOUT_USER_SUCCESS'
