export const TOAST_DISPLAY_INFO = 'TOAST_DISPLAY_INFO'
export const TOAST_DISPLAY_ERROR = 'TOAST_DISPLAY_ERROR'
export const TOAST_DISPLAY_SUCCESS = 'TOAST_DISPLAY_SUCCESS'
export const TOAST_DISPLAY_WARNING = 'TOAST_DISPLAY_WARNING'
